name: 提交/修正歌词 (实验性)
description: 我想通过实验性的流程提交/修正一个歌曲的 TTML 歌词文件！
title: "[实验性歌词提交/修正] "
labels: ["实验性歌词提交/修正"]
assignees:
  - Steve-xmh
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ 实验性流程警告
        你正在使用实验性的歌词处理流程。该流程尚在测试中，可能会遇到未知的 Bug，感谢你的参与和反馈！

  - type: input
    id: ttml-download-url
    attributes:
      label: TTML 歌词文件下载直链
      description: |
        Github Action 将会获取该链接指向的歌词文件数据并检查正确性
        确认无误后，Github Action 机器人将会在该 Issue 下方评论歌词文件数据原文供留存检查
        如果访问出错或格式有误，会导致你的 Issue 被直接关闭，请注意哦！
    validations:
      required: true

  - type: checkboxes
    id: lyric-options
    attributes:
      label: 歌词选项
      description: 选择歌词文件的选项
      options:
        - label: 这是逐行歌词
          required: false

  - type: dropdown
    id: upload-reason
    attributes:
      label: 提交缘由
      description: 是一首新歌曲的歌词呢？还是原来的歌词有疏漏或者错误呢？
      options:
        - 新歌词提交
        - 修正已有歌词
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### **高级选项**
        以下为高级处理选项，如果你不确定它们的作用，请保持默认哦

  - type: checkboxes
    id: advanced-toggles
    attributes:
      label: 功能开关
      description: 选择需要启用的功能
      options:
        - label: 启用自动分词

  - type: input
    id: punctuation-weight
    attributes:
      label: "[分词] 标点符号权重"
      description: "设置标点符号的时长权重。一个汉字的权重是 1.0。默认值: 0.3"
      placeholder: "0.3"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: comment
    attributes:
      label: 备注
      description: |
        有什么需要补充说明的呢？
        如果你所提交的歌曲中包含因特殊原因无法直接播放或获取的歌曲，建议提供一个音源下载链接，音质不做要求但是必须准确，这样可以方便审核哦！
    validations:
      required: false
