name: 同步上游分支

on:
  schedule:
    - cron: '0 0 */1 * *'
  branches: [upstream-base]
concurrency:
  group: sync
  cancel-in-progress: true

jobs:
  sync-from:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: Steve-xmh # fork 的上游仓库 user
          repo: amll-ttml-db # fork 的上游仓库 repo
          head: main # fork 的上游仓库 branch
          base: upstream-base # 本地仓库 branch
          token: ${{ secrets.GITHUB_TOKEN }}
