name: 同步 Github 到 Gitea [main]

on:
  # workflow_dispatch:
  workflow_run:
    workflows: [清除分支]
    branches: [main]
    types:
      - completed
concurrency:
  group: upload
  cancel-in-progress: true

jobs:
  sync-to:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Mask
        run: |
          echo "::add-mask::${{ secrets.PRIVATE_HOST }}"
          echo "::add-mask::${{ secrets.PRIVATE_PORT }}"
      # - name: Sync to Gitea
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEA_RSA_PRIVATE_KEY }}
      #   with:
      #     source-repo: git@github.com:ranhengzhang/amll-ttml-db-raw-data.git
      #     destination-repo: git@${{ secrets.PRIVATE_HOST }}:ranhengzhang/amll-ttml-db.git
      # - name: Git Config
      #   run: |
      #     git config user.name "ranhengzhang"
      #     git config user.password "${{ secrets.GITEA_TOKEN }}"
      - name: Sync to Gitea
        run: |
          git remote add gitea http://ranhengzhang:${{ secrets.GITEA_TOKEN }}@${{ secrets.PRIVATE_HOST }}:${{ secrets.PRIVATE_PORT }}/ranhengzhang/amll-ttml-db-raw-data.git
          git filter-branch -- --all
      - name: Push to Gitea
        run: git push gitea main --force
