name: 同步 Github 到 Gitee

on:
  workflow_run:
    workflows: [清除分支, 同步上游分支]
    types:
      - completed
concurrency:
  group: sync
  cancel-in-progress: true

jobs:
  sync-to:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:ranhengzhang/amll-ttml-db-raw-data.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:Lyre_of_Apollo/amll-ttml-db-raw-data.git
