name: 同步 Github 到 Gitea

on:
  workflow_dispatch:
  workflow_run:
    workflows: [清除分支, 同步上游分支]
    types:
      - completed
concurrency:
  group: sync
  cancel-in-progress: true

jobs:
  sync-to:
    runs-on: ubuntu-latest
    steps:
      - name: Mask
        run: echo "::add-mask::${{ secrets.PRIVATE_HOST }}"
      - name: Sync to Gitea
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEA_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:ranhengzhang/amll-ttml-db-raw-data.git
          destination-repo: git@${{ secrets.PRIVATE_HOST }}:ranhengzhang/amll-ttml-db.git
